/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ApiGeoStatsRouteImport } from './routes/api/geo-stats'
import { Route as ApiGuideRouteImport } from './routes/api/guide'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMapConfigRouteImport } from './routes/api/map-config'
import { Route as ApiSaveRouteImport } from './routes/api/save'
import { Route as ApiSearchTraceRouteImport } from './routes/api/search-trace'
import { Route as ApiPaymentsCallbackRouteImport } from './routes/api/payments/callback'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as BusinessIdRouteImport } from './routes/business/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTilesSplatRouteImport } from './routes/api/tiles/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoStatsRoute = ApiGeoStatsRouteImport.update({
  id: '/api/geo-stats',
  path: '/api/geo-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuideRoute = ApiGuideRouteImport.update({
  id: '/api/guide',
  path: '/api/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapConfigRoute = ApiMapConfigRouteImport.update({
  id: '/api/map-config',
  path: '/api/map-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveRoute = ApiSaveRouteImport.update({
  id: '/api/save',
  path: '/api/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchTraceRoute = ApiSearchTraceRouteImport.update({
  id: '/api/search-trace',
  path: '/api/search-trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCallbackRoute = ApiPaymentsCallbackRouteImport.update({
  id: '/api/payments/callback',
  path: '/api/payments/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTilesSplatRoute = ApiTilesSplatRouteImport.update({
  id: '/api/tiles/$',
  path: '/api/tiles/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/api/geo-stats': typeof ApiGeoStatsRoute
  '/api/guide': typeof ApiGuideRoute
  '/api/health': typeof ApiHealthRoute
  '/api/map-config': typeof ApiMapConfigRoute
  '/api/save': typeof ApiSaveRoute
  '/api/search-trace': typeof ApiSearchTraceRoute
  '/api/payments/callback': typeof ApiPaymentsCallbackRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/business/$id': typeof BusinessIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tiles/$': typeof ApiTilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/api/geo-stats': typeof ApiGeoStatsRoute
  '/api/guide': typeof ApiGuideRoute
  '/api/health': typeof ApiHealthRoute
  '/api/map-config': typeof ApiMapConfigRoute
  '/api/save': typeof ApiSaveRoute
  '/api/search-trace': typeof ApiSearchTraceRoute
  '/api/payments/callback': typeof ApiPaymentsCallbackRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/business/$id': typeof BusinessIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tiles/$': typeof ApiTilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/api/geo-stats': typeof ApiGeoStatsRoute
  '/api/guide': typeof ApiGuideRoute
  '/api/health': typeof ApiHealthRoute
  '/api/map-config': typeof ApiMapConfigRoute
  '/api/save': typeof ApiSaveRoute
  '/api/search-trace': typeof ApiSearchTraceRoute
  '/api/payments/callback': typeof ApiPaymentsCallbackRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/business/$id': typeof BusinessIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tiles/$': typeof ApiTilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/notifications'
    | '/api/geo-stats'
    | '/api/guide'
    | '/api/health'
    | '/api/map-config'
    | '/api/save'
    | '/api/search-trace'
    | '/api/payments/callback'
    | '/api/payments/webhook'
    | '/business/$id'
    | '/api/auth/$'
    | '/api/tiles/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/notifications'
    | '/api/geo-stats'
    | '/api/guide'
    | '/api/health'
    | '/api/map-config'
    | '/api/save'
    | '/api/search-trace'
    | '/api/payments/callback'
    | '/api/payments/webhook'
    | '/business/$id'
    | '/api/auth/$'
    | '/api/tiles/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/notifications'
    | '/api/geo-stats'
    | '/api/guide'
    | '/api/health'
    | '/api/map-config'
    | '/api/save'
    | '/api/search-trace'
    | '/api/payments/callback'
    | '/api/payments/webhook'
    | '/business/$id'
    | '/api/auth/$'
    | '/api/tiles/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ApiGeoStatsRoute: typeof ApiGeoStatsRoute
  ApiGuideRoute: typeof ApiGuideRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMapConfigRoute: typeof ApiMapConfigRoute
  ApiSaveRoute: typeof ApiSaveRoute
  ApiSearchTraceRoute: typeof ApiSearchTraceRoute
  ApiPaymentsCallbackRoute: typeof ApiPaymentsCallbackRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  BusinessIdRoute: typeof BusinessIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTilesSplatRoute: typeof ApiTilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo-stats': {
      id: '/api/geo-stats'
      path: '/api/geo-stats'
      fullPath: '/api/geo-stats'
      preLoaderRoute: typeof ApiGeoStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guide': {
      id: '/api/guide'
      path: '/api/guide'
      fullPath: '/api/guide'
      preLoaderRoute: typeof ApiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map-config': {
      id: '/api/map-config'
      path: '/api/map-config'
      fullPath: '/api/map-config'
      preLoaderRoute: typeof ApiMapConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save': {
      id: '/api/save'
      path: '/api/save'
      fullPath: '/api/save'
      preLoaderRoute: typeof ApiSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-trace': {
      id: '/api/search-trace'
      path: '/api/search-trace'
      fullPath: '/api/search-trace'
      preLoaderRoute: typeof ApiSearchTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/callback': {
      id: '/api/payments/callback'
      path: '/api/payments/callback'
      fullPath: '/api/payments/callback'
      preLoaderRoute: typeof ApiPaymentsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiles/$': {
      id: '/api/tiles/$'
      path: '/api/tiles/$'
      fullPath: '/api/tiles/$'
      preLoaderRoute: typeof ApiTilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ApiGeoStatsRoute: ApiGeoStatsRoute,
  ApiGuideRoute: ApiGuideRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMapConfigRoute: ApiMapConfigRoute,
  ApiSaveRoute: ApiSaveRoute,
  ApiSearchTraceRoute: ApiSearchTraceRoute,
  ApiPaymentsCallbackRoute: ApiPaymentsCallbackRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  BusinessIdRoute: BusinessIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTilesSplatRoute: ApiTilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
